name: offgrid_sos
description: Off-Grid SOS & Nearby Share App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  state_notifier: ^1.0.0
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  nearby_connections: ^4.3.0
  path: ^1.8.4
  http: ^1.2.1
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  flutter_blue_plus: ^2.0.0
  
  # Location and Media
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  mime: ^1.0.5
  
  # Background Tasks
  flutter_foreground_task: ^6.0.0+1
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
