name: offgrid_sos
description: Off-Grid SOS & Nearby Share App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_blue_plus: ^2.0.0
  nearby_connections: ^4.3.0
  sqflite: ^2.2.8+4
  path: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.13.0
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
