name: offgrid_sos
description: Off-Grid SOS & Nearby Share App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.0
  
  # Local Database
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.39
  sqflite: ^2.3.2
  path_provider: ^2.1.5
  
  # P2P Communication
  nearby_connections: ^4.3.0
  flutter_blue_plus: ^2.0.0
  
  # Location and Media
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  
  # System
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  
  # Background Tasks
  flutter_foreground_task: ^6.0.0+1
  
  # Utilities
  path: ^1.8.4
  http: ^1.2.1
  encrypt: ^5.0.3
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true
