name: offgrid_sos
description: Off-Grid SOS & Nearby Share App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  nearby_connections: ^4.3.0
  sqflite: ^2.2.8+4
  path: ^1.8.4
  http: ^1.2.1
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  flutter_blue_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  drift_dev: ^2.28.3

flutter:
  uses-material-design: true
