# Off-Grid SOS Integration Test Configuration
# ========================================

test_config:
  project_name: "Off-Grid SOS & Nearby Share"
  version: "1.0.0"
  flutter_channel: "stable"
  min_flutter_version: "3.0.0"
  
  # Test execution settings
  execution:
    timeout_seconds: 1800  # 30 minutes max per test suite
    retry_count: 2
    parallel_execution: false
    continue_on_failure: true
    
  # Environment requirements
  environment:
    required_tools:
      - flutter
      - dart
      - adb  # For Android testing
    
    android:
      min_sdk_version: 21
      compile_sdk_version: 34
      target_sdk_version: 34
      required_permissions:
        - "android.permission.ACCESS_FINE_LOCATION"
        - "android.permission.ACCESS_COARSE_LOCATION"
        - "android.permission.BLUETOOTH"
        - "android.permission.BLUETOOTH_ADMIN"
        - "android.permission.BLUETOOTH_CONNECT"
        - "android.permission.BLUETOOTH_ADVERTISE"
        - "android.permission.ACCESS_WIFI_STATE"
        - "android.permission.CHANGE_WIFI_STATE"
        - "android.permission.INTERNET"
        - "android.permission.WRITE_EXTERNAL_STORAGE"
        - "android.permission.READ_EXTERNAL_STORAGE"
    
    ios:
      min_deployment_target: "12.0"
      required_capabilities:
        - "location-services"
        - "bluetooth-le"
        - "wifi"

# Test categories and their configurations
test_categories:
  preflight:
    enabled: true
    timeout: 300
    tests:
      - flutter_installation
      - project_structure
      - dependencies
      - permissions
      
  code_analysis:
    enabled: true
    timeout: 600
    tests:
      - dart_analysis
      - code_formatting
      - code_comments
      - unused_imports
      
  unit_tests:
    enabled: true
    timeout: 900
    coverage_threshold: 80
    tests:
      - service_tests
      - provider_tests
      - model_tests
      - utility_tests
      
  integration_tests:
    enabled: true
    timeout: 1200
    tests:
      - service_coordinator
      - p2p_communication
      - sos_broadcasting
      - database_integration
      - ui_integration
      
  performance_tests:
    enabled: true
    timeout: 600
    benchmarks:
      app_startup_time: 3000  # milliseconds
      memory_usage_limit: 200  # MB
      battery_drain_limit: 5   # % per hour
      
  security_tests:
    enabled: true
    timeout: 300
    tests:
      - data_encryption
      - permission_handling
      - secure_communication
      - data_privacy
      
  cross_platform_tests:
    enabled: true
    timeout: 300
    platforms:
      - android
      - ios
      
  build_tests:
    enabled: true
    timeout: 1800
    build_types:
      - debug
      - release
    size_limits:
      debug_apk_max_mb: 100
      release_apk_max_mb: 50

# Service-specific test configurations
services:
  nearby_service:
    test_endpoints: 5
    connection_timeout: 30
    discovery_timeout: 60
    
  p2p_service:
    test_peers: 3
    connection_timeout: 45
    data_transfer_timeout: 30
    
  ble_service:
    scan_duration: 30
    connection_timeout: 20
    characteristic_timeout: 10
    
  location_service:
    accuracy_threshold: 100  # meters
    timeout: 30
    
  database_service:
    test_record_count: 1000
    query_timeout: 5
    
  sos_service:
    broadcast_timeout: 10
    response_timeout: 30

# Test data and scenarios
test_scenarios:
  message_delivery:
    - type: "text"
      content: "Test message for delivery verification"
      priority: "normal"
    - type: "emergency"
      content: "Emergency test message"
      priority: "critical"
    - type: "multimedia"
      content: "Test image/video message"
      priority: "normal"
      
  device_discovery:
    - scenario: "normal_discovery"
      expected_devices: 2
      timeout: 60
    - scenario: "sos_discovery"
      sos_active: true
      expected_rescuers: 1
      timeout: 30
      
  sos_scenarios:
    - type: "basic_sos"
      message: "Emergency assistance needed"
      location_required: true
    - type: "silent_sos"
      message: ""
      location_required: true
    - type: "group_sos"
      message: "Multiple people need help"
      location_required: true

# Report configuration
reporting:
  formats:
    - html
    - json
    - junit_xml
    
  output_directory: "test_results"
  
  include_screenshots: true
  include_logs: true
  include_coverage: true
  
  notifications:
    email:
      enabled: false
      recipients: []
    
    slack:
      enabled: false
      webhook_url: ""
      
    teams:
      enabled: false
      webhook_url: ""

# CI/CD Integration
ci_cd:
  github_actions:
    enabled: true
    workflow_file: ".github/workflows/integration_tests.yml"
    
  gitlab_ci:
    enabled: false
    config_file: ".gitlab-ci.yml"
    
  jenkins:
    enabled: false
    jenkinsfile: "Jenkinsfile"

# Quality gates
quality_gates:
  code_coverage:
    minimum_percentage: 80
    exclude_patterns:
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/generated/**"
      
  performance:
    app_startup_max_ms: 3000
    memory_usage_max_mb: 200
    
  security:
    vulnerability_scan: true
    dependency_check: true
    
  reliability:
    max_failed_tests: 0
    max_flaky_tests: 2